# Generated by Django 4.1 on 2022-10-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='is_finished',
        ),
    ]
